spring:
    datasource:
      url: jdbc:mysql://172.30.49.44/jetcache?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
logging:
  config: classpath:logback.xml

#jetcache:
#  statIntervalMinutes: 15
#  areaInCacheName: false
#  local:
#    default:
#      type: linkedhashmap
#      keyConvertor: fastjson
#  remote:
#    default:
#      type: redis
#      keyConvertor: fastjson
#      valueEncoder: java
#      valueDecoder: java
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: 127.0.0.1
#      port: 6379

#jetcache:
#  statIntervalMinutes: 15
#  areaInCacheName: false
#  hiddenPackages: com.alibaba
#  local:
#    default:
#      type: caffeine
#      limit: 100
#      keyConvertor: fastjson
#      expireAfterWriteInMillis: 100000
#    otherArea:
#      type: linkedhashmap
#      limit: 100
#      keyConvertor: none
#      expireAfterWriteInMillis: 100000
#  remote:
#    default:
#      type: redis
#      keyConvertor: fastjson
#      valueEncoder: java
#      valueDecoder: java
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${redis.host}
#      port: ${redis.port}
#    otherArea:
#      type: redis
#      keyConvertor: fastjson
#      valueEncoder: kryo
#      valueDecoder: kryo
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${redis.host}
#      port: ${redis.port}